# General config.
name: 'py_model'
version: '1.0.0'
config-version: 2

# Profile to use for database connection.
profile: 'dbt_recipes_py_profile'

# Functional directories.
model-paths: ['models']

# Build config.
target-path: 'target'  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - 'target'
  - 'dbt_packages'

# Models config.
models:
  py_model:
    +materialized: table
