version: '3.8'

services:
  postgres:
    image: postgres:10.23-alpine
    container_name: postgres_dbt_recipes
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_dev
    volumes:
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    networks:
      - dbt_recipes

networks:
  dbt_recipes:
