
# Append this section to ~/.dbt/profiles.yml if you haven't done so already
dbt_recipes_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: password
      dbname: db_dev
      schema: dbt_recipes
    prod:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: password
      dbname: db_prod
      schema: dbt_recipes
