
version: 2

models:
  - name: people
    description: "People in the world"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null

  - name: employees
    description: "Employee of acme company"
    columns:
      - name: id
        description: "Primary key"
        tests:
          - unique
          - not_null
