version: 2

models:
  - name: customer_orders
    description: 'Customers of an eCommerce site'
    columns:
      - name: customer_id
        description: 'Customer id'
      - name: customer_name
        description: 'Customer name'
      - name: address
        description: 'Customer address'
      - name: zip
        description: 'Customer zip code'
      - name: email
        description: 'Customer email address'
      - name: product_id
        description: 'Product id'
      - name: product_name
        description: 'Product name'
      - name: price
        description: 'Product price'
      - name: ordered_at
        description: 'Time when the order is placed'