version: 2

sources:
  - name: dbt_recipes
    database: db_dev
    schema: dbt_recipes
    tables:
      - name: customers
      - name: products
      - name: orders
        loaded_at_field: ordered_at
    freshness:
      warn_after:
        count: 2
        period: minute
      error_after:
        count: 1
        period: minute